### ISSUE TITLE
About the visualization?

### ISSUE THREAD

**Issue by huifu99** [sanjayss34/lm-listener#3]
Could you please upload some examples of 'audio_root' and 'video_root' in 'visualize_listener.py'?
I think it's necessary to provide all the full files for visualizing and inference.

**Comment by sanjayss34** [comment]
For this, you will need to have the raw data, which comes from https://github.com/evonneng/learning2listen . Please contact Evonne Ng (evonne_ng@berkeley.edu) to obtain the raw videos. Once you have the raw videos, you can obtain the audio for a video with this command:
```
ffmpeg -i /path/to/video.mp4 -ab 160k -ac 2 -ar 44100 -vn /path/to/audio.wav
```
Please let me know if you have more issues.

**Comment by slnrm** [comment]
Hello, I sent an email to evonne_ng@berkeley.edu before, but I didn't receive a reply. Is there any other way to contact her
