### ISSUE TITLE
where are the --audio_root and --video_root?

### ISSUE THREAD

**Issue by tranxuantuyen** [sanjayss34/lm-listener#9]
Hi, thank you for the awesome work.

Could you please tell me where I can find the --audio_root and --video_root for visualization? Are they the raw data, and is it possible for you to share them?

**Comment by sanjayss34** [comment]
Apologies for the delay. Yes, the --audio_root and --video_root refer to the raw data. If you would like to access the raw data, please email evonne_ng@berkeley.edu .

**Comment by junwenxiong** [comment]
Hi, i want to access the raw data, and also send the email to the address,  but no repsonse. Is there any other ways to access the data?
